version: '2.2'
services:
  ubuntu:
    image: "urlaub/ansibleclient:ubuntults"
    ports:
      - "1022:22"
  tansible:
    image: "urlaub/gollum"
    volumes:
      - ".:/gollum"
    ports:
      - "1337:80"
      - "4567"
